### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by tweksteen** [google/aff4#2]
c216333c6ebc114c5c81324c586d29ffdf52ca16 has broken the setup.py build:

    $ python setup.py sdist
    [...]
    UPDATING PyAFF4-0.19/pyaff4/_version.py
    error: [Errno 2] No such file or directory: 'PyAFF4-0.19/pyaff4/_version.py'

**Comment by scudette** [comment]
Sorry I had this fixed locally in order to publish the 0.19 release on pip.
It's kind of a chicken and egg since you can't know if the pip side is
broken until you try to push a new version and the version is fixed at a
git tag.
Am 23.11.2015 9:16 nachm. schrieb "Andreas Moser" <notifications@github.com
